In [1]:
import torch

In [2]:
preds = torch.randn(10,)
preds

tensor([-0.2983, -0.6965,  1.2035, -0.4537,  0.1763,  0.6844, -0.0930, -1.5428,
         0.1397,  0.1333])

In [13]:
target = torch.tensor([[0., 0., 0., 0., 0., 1., 1., 1., 1., 1.]])
target

tensor([[0., 0., 0., 0., 0., 1., 1., 1., 1., 1.]])

In [15]:
preds * target

tensor([[-0.0000, -0.0000,  0.0000, -0.0000,  0.0000,  0.6844, -0.0930, -1.5428,
          0.1397,  0.1333]])